# Generated by Django 6.1 on 2026-09-09 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('product_category_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=32)),
                ('customer_unique_id', models.CharField(max_length=32)),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.localisation')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=32)),
                ('order_purchase_timestamp', models.DateTimeField()),
                ('order_review', models.IntegerField(null=True)),
                ('order_delivered_carrier_date', models.DateTimeField()),
                ('order_estimated_delivery_date', models.DateField()),
                ('order_delivered_customer_date', models.DateTimeField()),
                ('order_status', models.CharField(max_length=32)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=32)),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.localisation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=12)),
                ('payment_installments', models.IntegerField()),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_sequential', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.order')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('payment_installments__gte', 0)), name='payment_installments_positive'), models.CheckConstraint(condition=models.Q(('payment_value__gte', 0)), name='payment_value_positive'), models.CheckConstraint(condition=models.Q(('payment_sequential__gte', 1)), name='payment_sequential_positive')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.seller')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='order_item_price_positive')],
            },
        ),
    ]
